# Generated by Django 5.2.1 on 2025-05-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="institution",
            new_name="course",
        ),
        migrations.AddField(
            model_name="customuser",
            name="current_Semester",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="customuser",
            name="current_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
