# Generated by Django 5.2.1 on 2025-05-13 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("A", "A (70–100%) – First Class Honours"),
                            ("B", "B (60–69%) – Second Class Honours Upper"),
                            ("C", "C (50–59%) – Second Class Honours Lower"),
                            ("D", "D (40–49%) – Pass"),
                            ("E", "E (0–39%) – Fail"),
                            (
                                "I",
                                "I – Incomplete / Missing Marks / Deferred due to Illness",
                            ),
                        ],
                        max_length=1,
                    ),
                ),
                ("semester", models.CharField(max_length=20)),
                ("year", models.PositiveIntegerField()),
                ("date_recorded", models.DateTimeField(auto_now_add=True)),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="grades.class",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
